### ISSUE TITLE
About random results

### ISSUE THREAD

**Issue by asd123pwj** [yuhuan-wu/P2T#15]
Excuse me, I recently encountered an issue where I trained a semantic segmentation model with the same configuration multiple times, and although the results are similar to what you reported in your paper, they appear to be random.

I was wondering if you could kindly provide some guidance on how to handle this randomness. 

Additionally, may I ask if it is appropriate to compare my best result among multiple experiments with your reported result?

**Comment by yuhuan-wu** [comment]
Good question. I think the issue you reported is mainly due to the limited dataset size. As I know, this issue even exists in MS COCO object detection with much larger dataset size.

When I implemented P2T on semantic FPN, I only ran 1-3 times for each backbone variant. If you reimplement the results, you may get a little bit higher or lower results than the numbers reported in our paper (as you mentioned). 
Some papers may introduce the variance number (+- xxx) to the results of the experiments and keep the fairness of each method. But most researchers only have limited computational resources, so it is a bit difficult to report the results with variance.
In a word, I agree that if you have abundant resources, you may run much more experiments to report the most reliable results.

**Comment by asd123pwj** [comment]
Thank you very much indeed.
